# BoardConfig.mk for TB375FC with TB373FU ZUI ROM

# Architecture definitions
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_CPU_ABI := arm64-v8a

# Platform and bootloader
TARGET_BOOTLOADER_BOARD_NAME := tb375fc
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6789
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

# DTB only — kernel removed
DEVICE_PATH := device/lenovo/tb375fc
BOARD_INCLUDE_DTB_IN_BOOTIMG := false
BOARD_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb

# Vendor_boot configuration
BOARD_VENDOR_RAMDISK_RECOVERY := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

# File systems
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_PARTITION_TYPE := f2fs

# Encryption support
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
