- name: Clone device tree
  run: |
    git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
  working-directory: ${{ steps.pwd.outputs.workspace-folder }}

- name: Add roomservice manifest
  run: |
    mkdir -p .repo/local_manifests
    cat <<EOF > .repo/local_manifests/roomservice.xml
<manifest>
  <project name="pcggrt55fbbike/device_lenovo_tb375fc_twrp" path="device/lenovo/tb375fc" remote="github" revision="newbuIld" />
</manifest>
EOF
  working-directory: ${{ steps.pwd.outputs.workspace-folder }}

- name: Repo Sync (with roomservice)
  run: |
    repo sync -j$(nproc --all) --force-sync
    echo "✅ repo sync completed including roomservice.xml device tree"
  working-directory: ${{ steps.pwd.outputs.workspace-folder }}
