# .github/workflows/main.yml
name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        default: 'twrp-12.1'
      DEVICE_TREE_URL:
        default: 'https://github.com/pcggrt55fbbike/device_lenovo_tb375fc_twrp'
      DEVICE_TREE_BRANCH:
        default: 'newbuIld'
      DEVICE_PATH:
        default: 'device/lenovo/tb375fc'
      COMMON_TREE_URL:
      COMMON_PATH:
      DEVICE_NAME:
        default: 'tb375fc'
      MAKEFILE_NAME:
        default: 'twrp_tb375fc'
      BUILD_TARGET:
        default: 'vendorboot'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Display Run Parameters
      run: |
        echo "🌐 Manifest: ${{ github.event.inputs.MANIFEST_URL }} [${{ github.event.inputs.MANIFEST_BRANCH }}]"
        echo "📦 Device Tree: ${{ github.event.inputs.DEVICE_TREE_URL }} [${{ github.event.inputs.DEVICE_TREE_BRANCH }}]"
        echo "📁 Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "📱 Device: ${{ github.event.inputs.DEVICE_NAME }} (${{
          github.event.inputs.MAKEFILE_NAME }}) ➜ Build target: ${{ github.event.inputs.BUILD_TARGET }}.img"

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt -y upgrade
        sudo apt install -y \
          gperf gcc-12 g++-12 g++-12-multilib gcc-12-multilib libc6-dev \
          libncurses5-dev libx11-dev tree lib32z-dev libgl1-mesa-dev \
          libxml2-utils xsltproc bc ccache lib32readline-dev liblz4-tool \
          libsdl1.2-dev libwxgtk3.2-dev lzop pngcrush schedtool squashfs-tools \
          imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-12-dev python3

    - name: Setup Java 8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8

    - name: Install repo tool
      run: |
        mkdir ~/bin
        curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod +x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace && cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "CopilotBot"
        git config --global user.email "copilot@example.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: pwd

    - name: Repo Sync
      run: repo sync -j$(nproc --all) --force-sync
      working-directory: workspace

    - name: Clone Device Tree
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} \
          -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} \
          ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Add roomservice manifest
      run: |
        mkdir -p .repo/local_manifests
        cat <<EOF > .repo/local_manifests/roomservice.xml
<manifest>
  <project name="pcggrt55fbbike/device_lenovo_tb375fc_twrp"
           path="device/lenovo/tb375fc"
           remote="github"
           revision="newbuIld" />
</manifest>
EOF
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Show Device Tree Structure
      run: tree ${{ github.event.inputs.DEVICE_PATH }} || ls -R ${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone Common Tree
      if: |
        github.event.inputs.COMMON_TREE_URL != null && github.event.inputs.COMMON_PATH != null
      run: |
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} \
          -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} \
          ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Detect Build Tree Type
      uses: haya14busa/action-cond@v1
      id: buildtree
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1' }}
        if_true: twrp
        if_false: omni

    - name: Sync Device Dependencies
      run: |
        bash ${GITHUB_WORKSPACE}/scripts/convert.sh \
          ${{ github.event.inputs.DEVICE_PATH }}/${{ steps.buildtree.outputs.value }}.dependencies || true
        repo sync -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Build Recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        if ! lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng; then
          echo "❌ lunch failed: combo not found: ${{ github.event.inputs.MAKEFILE_NAME }}-eng"
          lunch
          exit 1
        fi
        make clean
        make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload Artifact
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          🌿 Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          📱 Device: ${{ github.event.inputs.DEVICE_NAME }}
          🎯 Target: vendor_boot.img
          📦 Version: Android14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
